apiVersion: v1

kind: PersistentVolume

metadata:
  name: pv-volume1

spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 100Mi
  hostPath:
    path: /Users/AlicjaCh/Desktop/bartek/temp/k8s-volume1