apiVersion: v1

kind: Pod

metadata:
    name: myapp-pod
    labels:
        app: myapp
        type: frontend

spec:
    containers:
        - name: myfrontend-app
          imagePullPolicy: Never
          image: myfrontend-app
